adaptive: true
attention: true
drop_out: 0
graph: null
graph_args:
  layout: mediapipe_two_hand
  strategy: spatial
in_channels: 2
learning_rate: 0.0137296
num_class: 199
num_person: 1
num_point: 46
weight_decay: 0.000150403
